### ISSUE TITLE
Error on line 12, column 5: A dependency may only have one source.

### ISSUE THREAD

**Issue by lan2000** [zengxiangxi/photo_preview_flutter#1]
引用代码
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  photo_preview:
    git:
      url: https://github.com/zengxiangxi/photo_preview_flutter.git
      ref: master

报错：
Error on line 12, column 5: A dependency may only have one source.
   ╷
12 │ ┌     sdk: flutter
13 │ │     # 澶氬睘鎬у浘鐗?  extended_image:
14 │ │     git:
15 │ │       url: https://gitee.com/zengxiangxi315/extended_image.git
16 │ │       ref: latest
17 │ │   # UUID
18 │ │   uuid: ^2.2.0
   │ └──^
   ╵
pub get failed (65;    ╵)

**Comment by zengxiangxi** [comment]
Thanks for your comments, I will find time to correct the problem.

**Comment by zengxiangxi** [comment]
Whether your problem is that there is no problem with multiple versions, you can try to use 'dependency_overrides' in yaml to solve the problem.
