### ISSUE TITLE
怎么手动停止播放视频呢

### ISSUE THREAD

**Issue by lan2000** [zengxiangxi/photo_preview_flutter#3]
你好，在播放视频的页面，有些时候需要手动暂停播放视频，这个怎么实现？

**Comment by zengxiangxi** [comment]
最新版本已经更新了对自定义视频播放器的支持，可以看“自定义视频”的demo，可能对你有所帮助

**Comment by lan2000** [comment]
你好，能把video_player版本升级一下吗

**Comment by zengxiangxi** [comment]
已经是兼容性最新版本，video_player: ^0.10.11+1，或者用dependency_overrides 强行使用想要库的版本

**Comment by lan2000** [comment]
dependency_overrides: video_player: ^1.0.1
还是报错。
Because wechat_assets_picker &gt;=4.2.2 <5.0.0-dev.4 depends on extended_image from hosted and every version of photo_preview from git depends on extended_image from git, wechat_assets_picker &gt;=4.2.2 <5.0.0-dev.4 is incompatible with photo_preview from git.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zengxiangxi"<notifications@github.com&gt;; 
发送时间: 2021年2月4日(星期四) 晚上9:36
收件人: "zengxiangxi/photo_preview_flutter"<photo_preview_flutter@noreply.github.com&gt;; 
抄送: "若即若离若迷离"<122775467@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zengxiangxi/photo_preview_flutter] 怎么手动停止播放视频呢 (#3)





 
已经是兼容性最新版本，video_player: ^0.10.11+1，或者用dependency_overrides 强行使用想要库的版本

**Comment by lan2000** [comment]
引用如下：photo_preview:
  git:
    url: https://github.com/zengxiangxi/photo_preview_flutter
    ref: master


报另外一个错误：
Error on line 12, column 5: A dependency may only have one source.
&nbsp; &nbsp;╷
12 │ ┌&nbsp; &nbsp; &nbsp;sdk: flutter
13 │ │&nbsp; &nbsp; &nbsp;# 澶氬睘鎬у浘鐗?&nbsp; extended_image:
14 │ │&nbsp; &nbsp; &nbsp;git:
15 │ │&nbsp; &nbsp; &nbsp; &nbsp;url: https://gitee.com/zengxiangxi315/extended_image.git
16 │ │&nbsp; &nbsp; &nbsp; &nbsp;ref: latest
17 │ │&nbsp; &nbsp;# UUID
18 │ │&nbsp; &nbsp;uuid: ^2.2.0
&nbsp; &nbsp;│ └──^
&nbsp; &nbsp;╵
pub get failed (65;&nbsp; &nbsp; ╵)







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zengxiangxi/photo_preview_flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 晚上9:36
收件人:&nbsp;"zengxiangxi/photo_preview_flutter"<photo_preview_flutter@noreply.github.com&gt;;
抄送:&nbsp;"若即若离若迷离"<122775467@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zengxiangxi/photo_preview_flutter] 怎么手动停止播放视频呢 (#3)





 
已经是兼容性最新版本，video_player: ^0.10.11+1，或者用dependency_overrides 强行使用想要库的版本

**Comment by zengxiangxi** [comment]
这是你引用另一个库导致，我也没有办法。

**Comment by zengxiangxi** [comment]
这个是你另一个库引用了相同的extended_image导致冲突，这个extended_image也是fork下来了。你可以考虑fork修改源码解决冲突。

**Comment by zengxiangxi** [comment]
![image](https://user-images.githubusercontent.com/34399199/106904622-5fea0800-6736-11eb-90ea-cbfa1b05fa07.png)
或者尝试fork引入最新extended_image并按图修改该文件，从而解决冲突，不过不能保证可以完全解决问题。

**Comment by lan2000** [comment]
谢谢！最后还是弄下来，解决冲突，才搞定

**Comment by lan2000** [comment]
请大佬升级flutter2和空安全！

**Comment by zengxiangxi** [comment]
好的，我尽快适配

**Comment by lan2000** [comment]
你好，最新的flutter-2.x的分支已经在用。
有一点可以优化，当前进入视频播放页面，播放器初始化时候，界面中心显示播放按钮。网络差一些的时候这个过程很长，所以这个时候显示loading比较好。

**Comment by lan2000** [comment]
还有就是播放视频，设置loadingCoverUrl的功能好像失效了，多次测试并没有显示视频的封面。

**Comment by zengxiangxi** [comment]
好的，有时间我去优化下 @lan2000

**Comment by zengxiangxi** [comment]
可以加我QQ 634133722 随时沟通。 @lan2000
