### ISSUE TITLE
Support flutter 2.0 and null-safety!

### ISSUE THREAD

**Issue by HZRZCW** [zengxiangxi/photo_preview_flutter#4]
Please Support flutter 2.0 and null-safety!

**Comment by zengxiangxi** [comment]
I will consider your opinion.

**Comment by lan2000** [comment]
> I will consider your opinion.

thank you for the package!

Is this package going to migrate to Flutter 2 and Null safety?

**Comment by lan2000** [comment]
> Please Support flutter 2.0 and null-safety!

+1

**Comment by zengxiangxi** [comment]
@HZRZCW @lan2000 

The ‘flutter-2.x' branch has been submitted and flutter2 can be run. It is just a simple adaptation, and the details need to be optimized when there is time.

Feel free to contact if you have any questions.

thank u.
